name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ajuste para a branch que você usa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Ajuste isso para o diretório onde seus arquivos HTML estão localizados
